services:
  - type: web
    name: fcnmanager
    runtime: python
    buildCommand: apt-get update && apt-get install -y fonts-noto-cjk && pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
